### ISSUE TITLE
Création de la base de donnée

### ISSUE THREAD

**Issue by alexis-opolka** [alexis-opolka/Mon-Banzaii#11]
A faire:

- Une BD prototype en MySQL avec l'architecture principale et deux sets de données

- a attente de avoir les inforation a entré dans la base de donnée

**Comment by alexis-opolka** [comment]
Il faut créer la base de donnée complète avant le 01/06/2023.

**Comment by alexis-opolka** [comment]
L'échelon et la date de rendue a été mise à jour.

**Comment by LucasSimpol** [comment]
création des programme pour créer les donnée de façon aléatoire en cour

**Comment by LucasSimpol** [comment]
les deux programme sont ok pour créé les donnée, création du programme principale pour les lancer + création base de donnée
