### ISSUE TITLE
page.tsx

### ISSUE THREAD

**Issue by LucasSimpol** [alexis-opolka/Mon-Banzaii#7]

**Comment by LucasSimpol** [comment]
page d'accueil quand on arrive sur apt

**Comment by LucasSimpol** [comment]
image central a changé avec celle sans le text quand elle sera fait

**Comment by alexis-opolka** [comment]
Il faut que je m'en occupe, je me note ça à faire ce soir. 👍🏼

**Comment by LucasSimpol** [comment]
création ok plus cas intégré avec l'autentification + création de conte

**Comment by alexis-opolka** [comment]
Système d'authentification fonctionnel et intégré.
