### ISSUE TITLE
Authentication system

### ISSUE THREAD

**Issue by alexis-opolka** [alexis-opolka/Mon-Banzaii#8]
Add an authentication system using MYSQL as the database.

**Comment by LucasSimpol** [comment]
la page est avancé, je suis en attante d'avoir la partie web du formulaire pour pouvoir l'intégré

**Comment by alexis-opolka** [comment]
Le système d'authentification, dès qu'il est merge, devrait faire avancer les choses, je m'occupe en attendant de le nettoyer et de l'intégrer avec ta version de l'app.
N'hésites pas à merge sur `main` quand tu veux tes avancées sur le frontend.
